### ISSUE TITLE
I can't install add-on

### ISSUE THREAD

**Issue by legolas0802** [marcelveldt/hassio-addons-repo#1]
I press install, I see the circle that runs, after a while the install button turns red for a second.

**Comment by marcelveldt** [comment]
Which addon do you trybto install?

**Comment by legolas0802** [comment]
Google assistant web server, on hassio 64bit on Raspberry 3b +, HassOs 2.10 version hassio 0.88.1

**Comment by caiosweet** [comment]
Tested on the 32bit version and I have this error
Can't build 62c7908d/armhf-addon-google_assistant_webserver:0.0.4: The command '/bin/sh -c chmod a+x /run.sh' returned a non-zero code: 1

**Comment by sti0** [comment]
Is there any solution? Got the same error :-(

**Comment by friedit** [comment]
same here - but I can't install the auto backup

**Comment by caiosweet** [comment]
@sti0 @friedit this addons only works on amd64
