### ISSUE TITLE
Feature Request: Add these addons to Hassio sidebar

### ISSUE THREAD

**Issue by gsbrown** [marcelveldt/hassio-addons-repo#6]
Hey, great work with these addons; any chance you can make them available on the sidebar in Home Assistant?

**Comment by Madseason41** [comment]
+ 1, ingress support would be great.

**Comment by marcelveldt** [comment]
I'm refactoring all addons to be more compliant with Home Assistant, including Ingress support.
Spotweb and nzbget are ready to use, the others will follow next couple of days.

**Comment by MACscr** [comment]
Closed but not complete? Would really love sonarr and radarr ingress support.

**Comment by marcelveldt** [comment]
It's still in progress. It's a little more work than I anticipated before.

**Comment by MACscr** [comment]
Any luck with Sonarr and Radarr? =P
